apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: cp4i-apic
spec:
  encryptedData:
    .dockerconfigjson: AgCBdb09U+ORQ4t3AO+Rt393tPy06aaz9JAWTggy2EzxpYELmKzfbv4ZO1IZ6YfxzIbzWDAgMo704fjTViX3o4q45kjzPm9FfvOeYNoIyqNzn0jqr8RsNdABX91NsH4sdjOSa0KpPk/HFgbvWjbTJO15JiyLOWNYvfzLYXYJXCRWVsCSg0Sz5qPfXeiyLquH3+SAB32KT2YL8V7brCJjiFuIMqlP50+B6yzTTa2wIiZoaqMuXCBJc9c5SRqoe08m56E6yExQUcFNgaSNZzPfgihgmOrnd/jb11n9fNOTag2U0THjEl6kmrapWSfETacyPMgFKAInyOjVyJlDkOjXDTFLonf0kRDGQehK5OgxAxIuzizKjI01lfFPAbIiCxpjHa/X73vrj8PpViR8D1MS3+Pzy2rKOb+04s5W4BI+iCyc3AFwnicjzMO5+SSrlg9QiyeVK4m86ekltjndaaiLWV10qM7a+SzWhT4EFxB2dPyELc7ipcX7vkQO8A1R3E5Z4zuhqGXZEU9kVYMzzexVfk8oc/HmbVpPNaCf3sVgU9Qb+BA0SMz/NzZ3P5/XM8Dm2nQEIl8YeEN7VnwN6tK6J8HGryd3MDekyQVKHqffxvvafUoY1Fum0mYoQN8oEeBeibFkK629chYZl59oJw4GKavp4x+poib6lb3skVgdso9EykbOvT1xyatoPCrfkV7dKdXeyGabU3rLXcoeJJ7TW2ELU+WpmYgD9xtxurgLX4LCq3PBel3TxtUsa4Wx2/htQ9Ad0dVtDsP4HZ4E/ydJN8hQ6mPxqbhpcscPFqfcJTA6zqYXHGVqGLRDcwTkZYlqeimuYNaYkzJJ2XY7i6PPWhBI0pP+P//DAWb+lQyzW18y+gZKAjDHO9z8NhCCXwu7TyDt87Tpnj8hvjr2s5zGmhhH20+j0WeDuU5Xvo5vqhqrL7eA7HZHC8I8uUGGDOpFOVNVtj5+KXNkoL7OhUth0WuCZDEYedD6Q+ywI9KaDeH1ZHIrpwpzgDxRtJOVjJdL/7WDdeQJ5tiVIxsp+bg+8vig9TnbitAVf8C3QJF2tFNEi4sxF/Qq3nDk3nBXI3bjL6uD8/qqx2whYBhNi9vEom1/Z7wV9IBCUZplGNraenCS7XWZGNL810aRy9B1EpdKxZuiGa+UGR3aB0zySlukA/Zwegwx4Kpoukn1tG/y1svEvwaIJWlRu++rxnl0aWtZI3JQr3dKPxstOhBrNTrWvWBAsL+CC7Mj3Vo4FytvMsYItFQBuO+ycFm6w6C8/oqYrWc2J1/mcR69fCuXWP3k9Oa06VfnodycArKbI95ZE2vhQ5N/0qod9hJbERy/FNmMHjwn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: cp4i-apic
    type: kubernetes.io/dockerconfigjson

